export const FETCH_HANDICRAFTS_REQUEST = 'FETCH_HANDICRAFTS_REQUEST';

export const UPDATE_HANDICRAFT_CHECKED_REQUEST = 'UPDATE_HANDICRAFT_CHECKED_REQUEST';
export const UPDATE_HANDICRAFT_CANCELED_REQUEST = 'UPDATE_HANDICRAFT_CANCELED_REQUEST';
export const UPDATE_HANDICRAFT_VISITED_REQUEST = 'UPDATE_HANDICRAFT_VISITED_REQUEST';
